# Generated by Django 4.2.5 on 2023-09-21 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='cart',
        ),
        migrations.AddField(
            model_name='checkout',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.cart'),
            preserve_default=False,
        ),
    ]
