# Generated by Django 4.2.5 on 2023-09-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_product_favorite_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='status',
            field=models.CharField(choices=[('Favorite', 'Favorite')], max_length=255),
        ),
    ]
