# Generated by Django 4.2.5 on 2023-09-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_favorite_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='slug',
            field=models.CharField(choices=[('Home', 'Home'), ('Office', 'Office'), ('Friends', 'Friends'), ('Family', 'Family')], default='Home', max_length=255),
        ),
    ]
