# Generated by Django 4.2.5 on 2023-09-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='date_delivered',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='status',
            field=models.CharField(choices=[('Favorite', 'Favorite')], default='Favorite', max_length=255),
        ),
    ]
