# Generated by Django 4.2.5 on 2023-09-26 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_checkout_date_delivered_alter_favorite_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Addresse'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-date_created']},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='address',
        ),
        migrations.DeleteModel(
            name='CheckOut',
        ),
    ]
