# Generated by Django 4.2.5 on 2023-09-26 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
    ]
