# Generated by Django 4.2.5 on 2023-09-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='note',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
