# Generated by Django 4.2.5 on 2023-09-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_checkout_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='address',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
