# Generated by Django 4.2.5 on 2023-09-27 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_orderplaced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='quantity',
        ),
    ]
