# Generated by Django 4.2.5 on 2023-09-27 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_orderplaced_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderplaced',
            options={'ordering': ['-ordered_date']},
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='product',
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.cart'),
            preserve_default=False,
        ),
    ]
