# Generated by Django 4.2.5 on 2023-10-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_orderplaced_options_remove_orderplaced_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='cart',
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='product',
            field=models.ManyToManyField(to='core.product'),
        ),
    ]
