# Generated by Django 4.2.5 on 2023-10-02 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_orderplaced_cart_orderplaced_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='product',
            new_name='items',
        ),
    ]
